config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :users, controllers: {
        sessions: 'users/sessions'
      }

  resources :users
  resources :topics

  resources :skills

  resources :projects

  resources :events

  patch 'events/:id/leave', to: 'events#leave_event'

  get 'users/:id/email', to: 'users#email_volunteer'

  get 'users/:id/email-coordinator', to: 'users#email_coordinator'

  resources :skills_users

  get 'events/:id/marker', to: 'events#marker'

  get 'users/:id/email', to: 'users#email_volunteer'

  patch 'events/:id/join-event', to: 'events#join_event'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  # Loads photos through CarrierWave
  mount_uploader :photo, PhotoUploader

  has_many :projects
  has_many :events_users
  has_many :events, through: :events_users

  has_many :skills_users
  has_many :skills, through: :skills_users

  has_many :topics_users
  has_many :topics, through: :topics_users

  def self.total_volunteer_hours
    total_hours = 0
    all.each do |user|
      total_hours += user.users_hours
    end
    total_hours
  end

  def self.sort_by_hours
    all.sort_by {|user| user.users_hours }.reverse
  end

  def suggested_events
    Event.joins(:skills).where('end_date >= ?', Time.now).where({skills: {id: self.skills}}).distinct.limit(5)
  end

  def suggested_projects
    Project.where(topic_id:self.topics).distinct.limit(5)
  end

  def total_past_events
    self.events.where('end_date <= ?', Time.now)
  end

  def past_month_events
    total_past_events.where('end_date >= ?', Time.now.months_ago(2))
  end


  def matching_skills(event)
    matches = []
      event.skills.each do |skill|
        if self.skills.include?(skill)
          matches << skill.name
        end
      end
    matches
  end

  def users_hours
    sum = 0
    events.where('end_date <= ?', Time.now).each do |event|
     sum += event.calculate_hours
    end
    sum
  end

  def hours_received
    total_hours_received = 0
    projects.each do |project|
      total_hours_received += project.total_hours
    end
    total_hours_received
  end  

end

app/controllers/users/confirmations_controller.rb
class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class User::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :name, :bio, :location
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  #GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users/unlocks_controller.rb
class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @events = Event.all
    @suggested_events = @user.suggested_events
    @suggested_projects = @user.suggested_projects
  end

  def edit
     @user = User.find(params[:id])
     @skills_users = SkillsUser.find_by(user_id: params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(users_params)
    @skill = Skill.find(params[:skills_user][:skill])
    @skills_users = SkillsUser.find_by_user_id_and_skill_id(params[:id],params[:skills_user][:skill])
    if @skills_users == nil
      @user.skills << @skill
      @skills_users = SkillsUser.find_by_user_id_and_skill_id(params[:id],params[:skills_user][:skill])
      @skills_users.update(skill_description: params[:skills_user][:skill_description])
    else
      @skills_users.update(skill_description: params[:skills_user][:skill_description])
    end
    redirect_to user_path(params[:id])
  end

  def index
    if current_user == nil
      redirect_to new_user_session_path
    end
    @users = User.sort_by_hours
    @skills = Skill.all
  end

  def email_volunteer
    @user = User.find(params[:id])
    if params[:project_id] == "from user show page"
      sender_id = current_user.id
      @event = Event.find(1)
      UserMailer.contact_for_skills(@user,sender_id).deliver_now!
    else
      project = Project.find(params[:project_id])
      @event = Event.find(params[:event_id])
      UserMailer.contact_volunteer(@user,project,@event).deliver_now!
    end
    respond_to do |format|
      format.js
      format.html{redirect_to user_path(current_user.id)}
    end 
  end

  def email_coordinator
    coordinator = User.find(params[:id])
    UserMailer.contact_coordinator(coordinator, current_user).deliver_now!
     respond_to do |format|
      format.js
      format.html{redirect_to user_path(current_user.id)}
    end 
  end

  private
  def users_params
    params.require(:user).permit(:name, :email, :location, :bio, :photo, :photo_cache, {skill_ids: []}, {topic_ids: []})
  end

end

app/views/users/edit.html.erb
<div class="container">

          <!-- Form + Sidebar -->
          <div class="row">
            <div class="col-sm-6">
              <div class="heading mb20"><h4></span>Edit Your Profile</h4></div>
              <p class="mb20">Made a mistake when you signed up or have updated info? Make your changes here!</p>
              <%= form_for @user, html: {role: 'form'} do |f| %>
                          <div class="form-group">
                              <%= f.label :name %>: 
                              <%= f.text_field :name, autofocus: true, :cols => "75", class: 'form-control' %>
                          </div>

                          <div class="form-group">
                              <%= f.label :email %>:
                              <%= f.email_field :email, :cols => "75", :rows => "5", class: 'form-control' %>
                          </div>

                           <div class="form-group">
                             <%= f.label :location %>: 
                            <%= f.text_field :location, :cols => "75", class: 'form-control' %>
                          </div>

                          <div class="form-group">
                             <%= f.label :bio %>: 
                            <%= f.text_area :bio, :cols => "75", :rows => "5", class: 'form-control' %>
                          </div>

                          <div class="form-group">
                            <%= f.label :photo %>
                            <%= f.file_field :photo, class: "form-control" %><br>
                            <%= f.hidden_field :photo_cache %>
                          </div>


                          <p>What topics are you interested in?</p>
                      <div class="form-group">
                             <%= f.collection_check_boxes :topic_ids, Topic.all, :id, :name %>
                          </div>
          

                    </div>


                  <div class="col-sm-6">
              <div class="heading mb20"><h4>Add Your Skills</h4></div>
              <p class="mb20">Tell us about your skills! Pick a skill category from the dropdown menu and then write in your specific skills and how proficient you are at them!</p>
               <%= form_for @skills_users, url: {controller: :users, action: :update, id: @skills_users} do |f| %>
                          <div class="form-group">
                              <%= f.label :skill %>: 
                              <%= f.collection_select :skill, Skill.all, :id, :name %>
                          </div>

                          <div class="form-group">
                              <%= f.text_area :skill_description, :cols => "75", :rows => "5", class: 'form-control' %>
                          </div>

                          <%= f.submit "Update Your Skills" %>
                          
                      <% end %> 

                      
            
          
          <% end %>
                     </div>
            </div>
          
          </div>

        </div>

app/views/users/email_coordinator.js.erb
$("#coordinator-email a[action='email_coordinator']").on('click', '#coordinator-email').replaceWith('You successfully contacted Simone')

app/views/users/email_volunteer.js.erb
$('.suggested-volunteer-<%= @user.id %>-<%= @event.id %>').on('click', '.suggested-volunteer-<%= @user.id %>-<%= @event.id %>').replaceWith("You've successfully contacted <%= @user.name %>")

$('.contact-volunteer').on('click', '.contact-volunteer').replaceWith("You've successfully contacted <%= @user.name %>")

app/views/users/index.html.erb
<!-- <div class="header"><h1 class="text-uppercase mt10">There are <mark><%= @users.count %></mark> volunteers making a difference through Volunteerly.</h1></div> -->
      <!-- Begin Content Section -->
      <section class="mt40">
        <div id="portfolio" class="container">

          <!-- Begin Title -->
          <div class="row" data-sr="enter right">
            <div class="col-xs-4 col-xs-offset-4 text-center mb10">
              <div class="heading"><h4>Our Volunteers</h4></div>
           <p>Search volunteers by skill!</p>
            </div>
          </div>

          <!-- Portfolio Filter -->
          <div data-sr="enter left" class="row mb30">
            <ul class="nav nav-pills col-xs-12 text-center">
            <li class="filter col-sm-3" data-filter="all">All</li>
            <% @skills.each do |skill| %>
              <li class="filter col-sm-3" data-filter="<%= skill.class_slug %>"><%= skill.name %></li>
            <% end %>
            </ul>
          </div>

          <!-- Portfolio Items -->
          <div class="row">
            <ul id="myPortfolio" class="col-sm-12 text-center no-margin">
              <!-- Begin Item 1 -->
              <% @users.each_with_index do |user, index| %>
                <li onclick="" class="item <% user.skills.each do |skill| %><%= skill.class_slug %> <% end %> col-sm-2">
                <div class="view-circle img-circle portfolio-hover-1">
                <a href="users/<%= user.id %>">
                  <!-- Project Thumb -->
                  <% if user.photo.blank? %>
                  <%= image_tag("Volunteerly.jpg", class: "img-responsive") %>
                  <% else %>
                  <%= image_tag(user.photo, class: "img-responsive") %>
                  <% end %>
                     <div class="mask img-circle">
                        <div class="portfolio-hover-content">
                    </div><!-- /portfolio hover content -->
                  </div><!-- /mask-->
                </div><!-- /portfolio hover -->
                </a>
                <div class="portfolio-text mt20 mb5">
                    <h3 class="portfolio-title"><a href="single-project.html"><%= user.name %></a></h3>
                    <div class="project-title"><%= user.users_hours.to_i %> Hours</div>
<!--                     <% user.skills.each do |skill| %>
                    <div class="project-category"><%= skill.name %></div>
                    <% end %>
 -->
                </div>
              <!-- /list item -->
              <!-- End Item 1 -->
              </li>
              <% end %>
            </ul><!-- /portfolio ul -->
          </div><!-- /row -->

        </div><!-- /container -->
      </section><!-- /content -->
      <!-- End Content Section -->

    </div><!-- /boxed -->
  </div><!-- /bg boxed-->
  <!-- End Boxed or Fullwidth Layout -->

 
</body>
</html>

app/views/users/show.html.erb
<div class="row mt40">
  <div class="col-xs-4 col-xs-offset-4 text-center mb10">
    <div class="heading"><h4><%= @user.name %>'s Profile</h4></div>
  </div>
  <div class="col-xs-2 col-xs-offset-5 text-center">
    
    <% if current_user && current_user.id == @user.id %><%= link_to "Edit Your Profile", edit_user_path(@user.id), method: "get" %><% elsif current_user %>
 <div class="contact-volunteer">
  <%= button_to 'Contact this volunteer', "/users/#{@user.id}/email", method: :get, action: 'email_volunteer', remote: true, params: {project_id: "from user show page"}, class: 'btn btn-primary btn-rw', data: {confirm: "Are you sure you want to email #{@user.name}?"} %>
</div>
   
 <% end %>
  </div>
</div>


<div class="row">
  <div class="heading col-xs-12">
    <div class="view-circle img-circle">
   
    </div><!-- /img -->
    
  </div><!-- /col -->
</div><!-- /row -->
<!-- Cta -->
<div class="cta">
  <div class="row">
    <div class="col-xs-2">
      <div class="view-circle img-circle">
        <% if @user.photo.blank? %>
                  <%= image_tag("Volunteerly.jpg", class: "img-responsive") %>
                  <% else %>
                  <%= image_tag(@user.photo, class: "img-responsive") %>
                  <% end %>
      </div><!--/image-->
    </div><!--/col-->
    <div class="col-xs-6">
      <h4 class="text-uppercase heavy">Biography</h4>
      <p><%= @user.bio %></p>
      <h4 class="text-uppercase heavy mt20"><%= @user.name %> is passionate about:</h4>
      <ul class="list-unstyled">
        <% @user.topics.each do |topic| %>
          <li><%= topic.name %></li>
        <% end %>
      </ul>
      
    </div><!-- /col -->
    <div class="col-xs-4">
      <h4 class="text-uppercase heavy">Volunteer Stats</h4>
      <ul class="list-arrow-2-color no-margin">
        <li>Has volunteered <mark><%= @user.users_hours.to_i %></mark> total hours</li>
        <li><%= @user.name %> has volunteered for <mark><%= @user.total_past_events.count %></mark> events</li>
        <li><%= @user.name %> 's recent events include:</li>
        <% @user.past_month_events.each do |event| %>
              <li><%= event.name %></li>
        <% end %>
        <li>Has organized events utilizing <mark><%= @user.hours_received.to_i %></mark> volunteer hours</li>
      </ul>
    </div><!-- /col -->      
  </div><!-- /row -->
</div><!-- /cta -->

<div class="row mt40">
  <div class="content-box-bordered col-xs-offset-1 col-xs-10">
    <h4 class="heavy"><%= @user.name %> Is Skilled At</h4>
    <% if @user.skills %>
    
      <% @user.skills_users.each do |skills_users_row| %>
        <div class="col-xs-6">
        <h4><%= skills_users_row.skill.name %></h4>
        <p><%= skills_users_row.skill_description %></p>
        </div>
        <% end %>
  
    <% end %>
  </div><!-- /col -->
  
  
</div><!-- /row -->

 
    </div>
<hr class="double-hr mt20 mb20">
<% if current_user && current_user.id == @user.id && @user.projects %>
  <div class="row cta">
    <div class="col-xs-12 text-center">
      <% @user.projects.each do |project| %>
        <h4>You are a coordinator for the project <strong><%= project.name %></strong></h4>
        <%= link_to "Edit This Project", project_path(project.id) %>
      <% end %>
    </div><!-- /col -->
  </div><!-- /row -->
<% end %>
<hr class="mt20">

<% if current_user && current_user.id == @user.id %>
  <div class="row">
    <div class="col-xs-10 col-xs-offset-1 upcoming-events">
      <h4><mark>Your Upcoming Events</mark></h4>
      <% @user.events.each do |event| %>
        <div class="mb10 col-xs-4 upcoming-event-<%= event.id %>" >
          <h5 class="text-uppercase heavy"><%= event.truncated_name %></h5>
          <p><%= event.formatted_start %></p>
          <%= button_to 'Leave this event', "/events/#{event.id}/leave", method: :patch, remote: true%>
        </div><!-- /col -->
      <% end %>
    </div><!-- /upcoming events col -->
  </div><!-- /row -->
  <hr class="double-hr mt20 mb20">
<% end %>

<!-- SUGGESTED EVENTS -->
<% if current_user && current_user.id == @user.id %>    
<section class="row cta">
  <div class="col-xs-6">
    <h3><strong>Suggested Events</strong></h3>
        <% @suggested_events.each do |event| %>
          <% if !@user.events.include?(event) %>
            <h4><strong><%= event.name %></strong></h4>
            <div class="suggested-event<%= event.id %>">
            <%= button_to "Join This Event!!", event_path(event.id), method: :patch, remote: true, id: "suggested-events" %>
            </div>
            <div class="join-alert-<%= event.id %>"></div>
            <p><%= event.description %></p>
            <p><%= event.formatted_start %> - <%= event.formatted_end %></p>
            <p>This event was suggested based on these skills:</p> 
            <% @user.matching_skills(event).each_with_index do |skill, i| %>
            <% if i > 0 %>
              -<%= skill %>
            <% else %>
              <%= skill %>
            <% end %>
          <% end %>
        <% end %>
          <% end %>                   
          
        </div><!-- suggested-event AJAX -->
      
  </div><!--/col-->
  <div class="col-xs-6">
    <h3><strong>Suggested Projects</strong></h3>
    <% @suggested_projects.each do |project| %>
      <h4 class="text-white"><%= link_to project.name, project_path(project.id) %></h4>
      <p>This project was suggested based on your interest in: <%= project.topic.name %></p>
    <% end %>




  </div><!--/col-->
</section>
<% end %>





  <% if current_user && current_user.id == @user.id %>    
<section class="row cta">
    <div class="col-xs-10 col-xs-offset-1">
      <div class="col-xs-12 col-sm-6">
        
      </div><!-- /col -->        
    </div><!-- /col offset -->
    <div class="col-xs-12 col-sm-6">  
      <h3><strong>Some more events you can sign up for.</strong></h3>
      <% @events.each_with_index do |event, i| %>
        <% if !@user.events.include?(event) %>  
          <div class="suggested-event-<%= event.id %>">   
            <%= button_to "Join This Event!!", "/events/#{event.id}/join-event", method: :patch, remote: true, class: "suggested-events" %>
            <div class="join-alert-<%= event.id %>"></div>
            <p><%= event.description %></p>
            <p><%= event.formatted_start %> - <%= event.formatted_end %></p>
            <% break if i > 2 %>
          </div><!-- suggested-event AJAX --> 
        <% end %>
      <% end %>              
    </div><!-- /col -->
</section><!-- /cta --> 

  <% end %>