config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :users, controllers: {
        sessions: 'users/sessions'
      }

  resources :users
  resources :topics

  resources :skills

  resources :projects

  resources :events

  patch 'events/:id/leave', to: 'events#leave_event'

  get 'users/:id/email', to: 'users#email_volunteer'

  get 'users/:id/email-coordinator', to: 'users#email_coordinator'

  resources :skills_users

  get 'events/:id/marker', to: 'events#marker'

  get 'users/:id/email', to: 'users#email_volunteer'

  patch 'events/:id/join-event', to: 'events#join_event'

end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :events
  belongs_to :topic
  belongs_to :user
  mount_uploader :photo, PhotoUploader

  def total_hours
    hours = 0
    events.where('end_date <= ?', Time.now).each do |event|
      hours += (event.calculate_hours * event.users.count)
    end
    hours
  end 

  def total_users
    users = 0
    events.each do |event|
      users += event.users.count
    end
    users
  end

  def truncated_name
    name.truncate(25)
  end

  def truncated_description
    description.truncate(90) 
  end

  def future_events
    events.where('start_date >= ?', Time.now).order(:start_date)
  end

  def past_events
    events.where('start_date <= ?', Time.now).order(:start_date)
  end

  
  
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.all
  end

  def show
    @project = Project.find(params[:id])
  end

  def edit
    @project = Project.find(params[:id])
    @users = User.all 
  end

  def update
    # binding.pry
    project = Project.find(params[:id])
    project.update(new_event_params)
    start_date = DateTime.new(params[:project][:events]["start_date(1i)"].to_i,params[:project][:events]["start_date(2i)"].to_i,params[:project][:events]["start_date(3i)"].to_i,params[:project][:events]["start_date(4i)"].to_i,params[:project][:events]["start_date(5i)"].to_i)
    end_date = DateTime.new(params[:project][:events]["end_date(1i)"].to_i,params[:project][:events]["end_date(2i)"].to_i,params[:project][:events]["end_date(3i)"].to_i,params[:project][:events]["end_date(4i)"].to_i,params[:project][:events]["end_date(5i)"].to_i)
    event = Event.create(name: params[:project][:events][:name], description: params[:project][:events][:description], address: params[:project][:events][:address],start_date: start_date, end_date: end_date)
    project.events << event
    redirect_to project_path(project.id)
  end

  private

  def new_event_params
    params.require(:project).permit(:name, :neighborhood, :description, :photo, :photo_cache)
  end



end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/edit.html.erb
<h1>Edit Your Project</h1>
<div class="row">
  <div class="col-xs-12">
  <%= form_for @project do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name, autofocus: true %><br>
    <%= f.label :neighborhood %>
    <%= f.text_field :neighborhood %><br>
    <%= f.label :description %>
    <%= f.text_area :description %><br>
    <%= f.label :photo %>
    <%= f.file_field :photo, class: "form-control" %>
    <%= f.hidden_field :photo_cache %>
    <h3>Add Events to Your Project!</h3>
    <%= f.fields_for :events do |event_form| %>
      <%= event_form.label :name %>
      <%= event_form.text_field :name %>
      <%= event_form.label :description %>
      <%= event_form.text_field :description %><br>
      <%= event_form.label :address %>
      <%= event_form.text_field :address %><br>
      <%= event_form.label :start_date, "When will this event begin?" %>
      <%= event_form.datetime_select(:start_date, ampm: true, default: 1.days.from_now)  %><br>
      <%= event_form.label :end_date, "When will this event end?" %>
      <%= event_form.datetime_select(:end_date, ampm: true, default: 1.days.from_now)  %><br>
    <% end %> 
    <%= f.submit %>
  </div> 
<% end %>
</div>

app/views/projects/index.html.erb
<!-- Begin Title -->
          
          <div class="row mt40">
            <div class="col-xs-4 col-xs-offset-4 text-center mb10">
              <div class="heading"><h4>Our Projects</h4></div>
           <p><%= Project.count %> projects seeking volunteers like you!</p>
            </div>
          </div>

<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
  <table class="table table-hover">
      <thead>
          <tr>
              <th>Project Name</th>
              <th>Topic</th>
              <th>Neighborhood</th>
              <th>Description</th>
          </tr>
      </thead><!-- /table header -->  
      <tbody>
      <% @projects.each do |project| %>
          
          <tr>
              <td><%= link_to project.truncated_name, project_path(project.id) %></td>
              <td><%= link_to project.topic.name, project_path(project.id) %></td>
              <td><%= link_to project.neighborhood, project_path(project.id) %></td>
              <td><%= link_to project.truncated_description, project_path(project.id) %></td>
          </tr>
        
      <% end %>
      </tbody><!-- /table body -->  
  </table><!-- /hover table -->
  </div>
</div><!-- /row -->

app/views/projects/show.html.erb
<div class="container">

  <!-- PROJECT INTRO -->
  <div class="row mt40">
    <div class="col-xs-7">
      <div class="heading mt30-xs">
        <h4><%= @project.name %></h4>
      </div>
      <p>
        <%= @project.description %>
      </p>
      <div class="ml20 mt20">
      <h5>Project at a glance:</h5>
        <ul class="list-arrow-2-color ml20">
          <li id="coordinator-email">The coordinator for this project is <%= link_to @project.user.name, user_path(@project.user_id) %>
          <% if current_user %>
            - <%= link_to "(email #{@project.user.name})", "/users/#{@project.user_id}/email-coordinator", action: 'email_coordinator', remote: true, data: {confirm: "Are you sure you want to email Project Coordinator #{@project.user.name}?"} %>
          <% end %>
          </li>
          <li>This project has utilized <mark><%= @project.total_hours.to_i %></mark> total volunteer hours</li>
          <li>This project has hosted <mark><%= @project.events.count %></mark> events</li>
          <li><mark><%= @project.total_users.to_i %></mark> volunteers have contributed to this project</li>
        </ul>
      </div><!-- /ml20 -->
    </div><!-- /col-sm-7 -->
    <div class="col-xs-5">
    <%= image_tag("brooklyn_photo.jpg", :class => "img-responsive") %>
    <p class="text-right"><small>Photo uploaded by Adam</small></p>
    </div><!-- /col-sm-5 -->
  </div><!-- /row -->

  <!-- UPCOMING EVENTS -->
  <div class="row mt20">
    <div class="col-xs-12">
      <div class="heading mt30-xs">
        <h4>Upcoming Events</h4>
      </div>
      <% @project.future_events.each do |event| %>
        <div class="col-xs-4">
          <h4 class="mt10"><%= link_to event.name, event_path(event.id) %></h4>
          <p><%= event.formatted_start %> - <%= event.formatted_end %></p>
          <% if current_user && current_user.events.include?(event) %>
            <%= button_to "Leave this event", "/events/#{event.id}/leave", method: :patch, remote: true, class: "btn btn-rw btn-primary btn-xs upcoming-event-#{event.id}" %>
          <% elsif current_user %>
            <%= button_to "Join This Event",  "/events/#{event.id}/join-event", method: :patch, remote: true, class: "btn btn-rw btn-primary btn-xs, suggested-event-#{event.id}"%>
          <% end %>
        </div>
      <% end %>
    </div><!-- /col-xs-12 -->
  </div>

   <!-- PROJECT COORDINATOR DASHBOARD -->
   <% if current_user && @project.user_id == current_user.id %>
  <div class="row mt40">
    <div class="col-xs-12">
      <div class="heading mt30-xs">
       
          <h4>Project Coordinator Dashboard</h4>
            <%= link_to 'Click here to add events or edit project name & description', edit_project_path(@project.id),method: :get %>
      
      </div>
          <div class="col-sm-6 mt20">
            <h4>Future Events</h4>
            <% @project.future_events.each do |event| %>

              <h5 class="ml20"><%= event.name %> <small><%= event.formatted_start %> <%= link_to "Edit this event", edit_event_path(event.id) %></small><small><%= link_to "Delete this event", event_path(event.id), method: :delete, data: {confirm: "Are you sure?"}, remote: true %></small></h5>
            <% end %>
          </div><!--/future events-->
          <div class="col-sm-6 mt20">
            <h4>Past Events</h4>
            <% @project.past_events.each do |event| %>
              <h5 class="ml20"><%= event.name %> <small><%= event.formatted_start %> <%= link_to "Edit this event", edit_event_path(event.id) %></small> </h5>
            <% end %>
          </div><!--/past events-->


      </div>
      <% else %>
      <hr class="mb40">
      <% end %>
    </div>
  </div>


</div><!-- /container -->