config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :users, controllers: {
        sessions: 'users/sessions'
      }

  resources :users
  resources :topics

  resources :skills

  resources :projects

  resources :events

  patch 'events/:id/leave', to: 'events#leave_event'

  get 'users/:id/email', to: 'users#email_volunteer'

  get 'users/:id/email-coordinator', to: 'users#email_coordinator'

  resources :skills_users

  get 'events/:id/marker', to: 'events#marker'

  get 'users/:id/email', to: 'users#email_volunteer'

  patch 'events/:id/join-event', to: 'events#join_event'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>VolunteerApp</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <%= analytics_init if Rails.env.production? %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Volunteerly</a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
          <% if current_user != nil %>
            <li><%= link_to('Sign Out', destroy_user_session_path, method: 'delete') %><span class="sr-only"></span></a></li>
            <li><%= link_to('Your Dashboard', user_path(current_user.id)) %></li>
            <li><%= link_to('All Volunteers', users_path) %></li>
          <% else %>
            <li><%= link_to('Sign In', new_user_session_path) %><span class="sr-only"></span></a></li>
          <% end %> 
            <li><%= link_to('All Projects', projects_path) %><span class="sr-only"></span></a></li>
            <li class="mt10"><mark><%= User.all.count %></mark> Volunteers and Counting<span class="sr-only"></span><br><br>
              <span class="mt10"><mark><%= Event.count %></mark> Events improving NYC</span><br>
          
            </a></li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>

  <%= yield %>

    <footer class="footer">
      <div class="container">
        <!--=== Copyright ===-->
        <div class="row">
          <div class="col-sm-12 text-center">
            <p class="mb15">
              <h4 class="footer-title"><strong>Volunteerly was built by:</strong></h4>
              <span> <a href="https://github.com/aczerepinski" class="fa fa-github">Adam Czerepinski ~</a><a href="https://github.com/sim1hill" class="fa fa-github">Simone Hill</a><a href="https://github.com/joshuadbaker/" class="fa fa-github">~ Joshua Baker</a></span>
            </p>
        </div><!-- /row -->
      </div><!-- /container -->
    </footer><!-- /footer -->
  </body>
</html>